### ISSUE TITLE
Question: access to the full Shepherd API?

### ISSUE THREAD

**Issue by sfc32** [actmd/abraham#64]
The Abraham documentation talks about steps, and the example has `element` and `placement`

```
   title: "Events"
      text: "If you're participating in any events today, we'll show that here."
      attachTo:
        element: ".dashboard-events"
        placement: "right"
```

The Shepherd API offers many other options on the [Step object](https://shepherdjs.dev/docs/Step.html#Step), including `popperOptions`, `highlightClass`, `arrow` etc.

Does Abraham support all of these options?

https://shepherdjs.dev/docs/
